export const FETCH_USER_ACTIVITY_SUCCESS = 'FETCH_USER_ACTIVITY_SUCCESS';
export const FETCH_USER_ACTIVITY_IN_PROGRESS = 'FETCH_USER_ACTIVITY_IN_PROGRESS';
export const FETCH_USER_ACTIVITY_ERROR = 'FETCH_USER_ACTIVITY_ERROR';

export const FETCH_COLLECTION_ACTIVITY_SUCCESS = 'FETCH_COLLECTION_ACTIVITY_SUCCESS';
export const FETCH_COLLECTION_ACTIVITY_IN_PROGRESS = 'FETCH_COLLECTION_ACTIVITY_IN_PROGRESS';
export const FETCH_COLLECTION_ACTIVITY_ERROR = 'FETCH_COLLECTION_ACTIVITY_ERROR';
