export const PLACE_BID_DIALOG_SHOW = 'PLACE_BID_DIALOG_SHOW';
export const PLACE_BID_DIALOG_HIDE = 'PLACE_BID_DIALOG_HIDE';
export const PLACE_BID_SUCCESS_SET = 'PLACE_BID_SUCCESS_SET';
export const PLACE_BID_FAIL_SET = 'PLACE_BID_FAIL_SET';

export const FETCH_AUCTION_LISTINGS_SUCCESS = 'FETCH_AUCTION_LISTINGS_SUCCESS';
export const FETCH_AUCTION_LISTINGS_IN_PROGRESS = 'FETCH_AUCTION_LISTINGS_IN_PROGRESS';
export const FETCH_AUCTION_LISTINGS_ERROR = 'FETCH_AUCTION_LISTINGS_ERROR';

export const AUCTIONS_SORT_SET = 'AUCTIONS_SORT_SET';
export const AUCTIONS_SEARCH_SET = 'AUCTIONS_SEARCH_SET';

export const COLLECTION_AUCTION_FILTERS_SHOW = 'COLLECTION_AUCTION_FILTERS_SHOW';
export const COLLECTION_AUCTION_FILTERS_HIDE = 'COLLECTION_AUCTION_FILTERS_HIDE';
export const CA_PRICE_RANGE_COIN_SET = 'CA_PRICE_RANGE_COIN_SET';
export const CA_PRICE_RANGE_SET = 'CA_PRICE_RANGE_SET';
export const CA_ON_SALE_IN_SET = 'CA_ON_SALE_IN_SET';
export const CA_ON_SALE_IN_SEARCH_SET = 'CA_ON_SALE_IN_SEARCH_SET';
export const CA_AUCTION_TYPE_SET = 'CA_AUCTION_TYPE_SET';

export const LISTING_AUCTION_FILTERS_SHOW = 'LISTING_AUCTION_FILTERS_SHOW';
export const LISTING_AUCTION_FILTERS_HIDE = 'LISTING_AUCTION_FILTERS_HIDE';
export const LA_PRICE_RANGE_COIN_SET = 'LA_PRICE_RANGE_COIN_SET';
export const LA_PRICE_RANGE_SET = 'LA_PRICE_RANGE_SET';
export const LA_ON_SALE_IN_SET = 'LA_ON_SALE_IN_SET';
export const LA_ON_SALE_IN_SEARCH_SET = 'LA_ON_SALE_IN_SEARCH_SET';
export const LA_AUCTION_TYPE_SET = 'LA_AUCTION_TYPE_SET';
