export const FETCH_HOME_COLLECTIONS_IN_PROGRESS = 'FETCH_HOME_COLLECTIONS_IN_PROGRESS';
export const FETCH_HOME_COLLECTIONS_SUCCESS = 'FETCH_HOME_COLLECTIONS_SUCCESS';
export const FETCH_HOME_COLLECTIONS_ERROR = 'FETCH_HOME_COLLECTIONS_ERROR';

export const FETCH_LAUNCHPAD_COLLECTIONS_IN_PROGRESS = 'FETCH_LAUNCHPAD_COLLECTIONS_IN_PROGRESS';
export const FETCH_LAUNCHPAD_COLLECTIONS_SUCCESS = 'FETCH_LAUNCHPAD_COLLECTIONS_SUCCESS';
export const FETCH_LAUNCHPAD_COLLECTIONS_ERROR = 'FETCH_LAUNCHPAD_COLLECTIONS_ERROR';

export const LAUNCHPAD_COLLECTION_SEARCH_SET = 'LAUNCHPAD_COLLECTION_SEARCH_SET';

export const FETCH_STATS_IN_PROGRESS = 'FETCH_STATS_IN_PROGRESS';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_ERROR = 'FETCH_STATS_ERROR';
