export const FETCH_OWNER_COLLECTIONS_SUCCESS = 'FETCH_OWNER_COLLECTIONS_SUCCESS';
export const FETCH_OWNER_COLLECTIONS_IN_PROGRESS = 'FETCH_OWNER_COLLECTIONS_IN_PROGRESS';
export const FETCH_OWNER_COLLECTIONS_ERROR = 'FETCH_OWNER_COLLECTIONS_ERROR';

export const FETCH_OWNER_NFT_S_SUCCESS = 'FETCH_OWNER_NFT_S_SUCCESS';
export const FETCH_OWNER_NFT_S_IN_PROGRESS = 'FETCH_OWNER_NFT_S_IN_PROGRESS';
export const FETCH_OWNER_NFT_S_ERROR = 'FETCH_OWNER_NFT_S_ERROR';

export const FETCH_USER_COLLECTIONS_SUCCESS = 'FETCH_USER_COLLECTIONS_SUCCESS';
export const FETCH_USER_COLLECTIONS_IN_PROGRESS = 'FETCH_USER_COLLECTIONS_IN_PROGRESS';
export const FETCH_USER_COLLECTIONS_ERROR = 'FETCH_USER_COLLECTIONS_ERROR';

export const FETCH_USER_NFT_S_SUCCESS = 'FETCH_USER_NFT_S_SUCCESS';
export const FETCH_USER_NFT_S_IN_PROGRESS = 'FETCH_USER_NFT_S_IN_PROGRESS';
export const FETCH_USER_NFT_S_ERROR = 'FETCH_USER_NFT_S_ERROR';

export const FETCH_USER_BALANCE_SUCCESS = 'FETCH_USER_BALANCE_SUCCESS';
export const FETCH_USER_BALANCE_IN_PROGRESS = 'FETCH_USER_BALANCE_IN_PROGRESS';
export const FETCH_USER_BALANCE_ERROR = 'FETCH_USER_BALANCE_ERROR';

export const DEPOSITE_DIALOG_SHOW = 'DEPOSITE_DIALOG_SHOW';
export const DEPOSITE_DIALOG_HIDE = 'DEPOSITE_DIALOG_HIDE';

export const WITHDRAW_DIALOG_SHOW = 'WITHDRAW_DIALOG_SHOW';
export const WITHDRAW_DIALOG_HIDE = 'WITHDRAW_DIALOG_HIDE';

export const AMOUNT_VALUE_SET = 'AMOUNT_VALUE_SET';

export const NFT_TRANSFER_IN_PROGRESS = 'NFT_TRANSFER_IN_PROGRESS';
export const NFT_TRANSFER_SUCCESS = 'NFT_TRANSFER_SUCCESS';
export const NFT_TRANSFER_ERROR = 'NFT_TRANSFER_ERROR';

export const CLEAR_MY_ACCOUNT_DATA = 'CLEAR_MY_ACCOUNT_DATA';
